<?php

/*
 * COPYRIGHT 2011
 *
 * The Regents of the University of Michigan
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * any later version.
 *
 * You may not use the name of The University of Michigan in any
 * advertising or publicity pertaining to the use of distribution of this software
 * without specific, written prior authorization. If the above copyright notice
 * or any other identification of the University of Michigan is included in any
 * copy of any portion of this software, then the disclaimer below must
 * also be included.
 *
 * THIS SOFTWARE IS PROVIDED AS IS, WITHOUT REPRESENTATION
 * FROM THE UNIVERSITY OF MICHIGAN AS TO ITS FITNESS FOR ANY
 * PURPOSE, AND WITHOUT WARRANTY BY THE UNIVERSITY OF
 * MICHIGAN OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING
 * WITHOUT LIMITATION THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE
 * REGENTS OF THE UNIVERSITY OF MICHIGAN SHALL NOT BE LIABLE
 * FOR ANY DAMAGES, INCLUDING SPECIAL, INDIRECT, INCIDENTAL, OR
 * CONSEQUENTIAL DAMAGES, WITH RESPECT TO ANY CLAIM ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OF THE SOFTWARE, EVEN
 * IF IT HAS BEEN OR IS HEREAFTER ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGES.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * module to place "cancel" button in the right place next to "submit"
 * button after installing "captcha" for the "contact-mail-form"
 */
function oercancelbutton_form_alter(&$form, $form_state, $form_id){
  if($form_id == 'webform_client_form_258'){
    if (isset($form['actions']) && is_array($form['actions'])) {
      $form['actions']['cancel'] = array(
        '#type' => 'button',
        '#value' => t('Cancel'),
        '#id' => 'oercancelbutton_form',
        '#weight' => 15,
        '#attributes' => array('class' => 'form-cancel', 'onClick' => 'location.replace("'. referer_uri() .'"); return false;'),
        // some more params....
      );
    } else {
      $form['cancel'] = array(
        '#type' => 'button',
        '#value' => t('Cancel'),
        '#id' => 'oercancelbutton_form',
        '#weight' => 1005,
        '#attributes' => array('class' => 'form-cancel', 'onClick' => 'location.replace("'. referer_uri() .'"); return false;'),
        // some more params....
      );
    }
  }

  if ($form_id == 'search_form') {
    $form['basic']['#title'] = '';
    $form['advanced']['#type'] = 'hidden';
    // $form['basic']['#type'] = 'hidden';
  }
}
?>
