<?php
// $Id: blocks404.install,v 1.2 2010/03/25 18:43:43 johnalbin Exp $

/**
 * Implements hook_enable().
 *
 * If site_404 is not set, all menu-related items disappear on 404.
 */
function blocks404_enable() {
  if (variable_get('site_404', '') == '') {
    variable_set('site_404', BLOCKS404_PAGE);
  }
}

/**
 * Implements hook_disable().
 */
function blocks404_disable() {
  if (variable_get('site_404', '') == BLOCKS404_PAGE) {
    variable_set('site_404', '');
  }
}
