<?php
// $Id: views_bonus_paged_feed.views.inc,v 1.1 2010/01/07 21:19:05 neclimdul Exp $

/**
 * @file
 * Views API hooks for views_bonus_paged_feed.
 */

/**
 * Implementation of hook_views_plugins
 */
function oer_feed_views_plugins() {
  return array(
    // Style plugins
    'style' => array(
      'oer-rss' => array(
        'title' => t('OER RSS Feed'),
        'help' => t('Generates an extended RSS feed including the parent node from a view.'),
        'handler' => 'oer_feed_plugin_style_rss',
        'path' => drupal_get_path('module', 'oer_feed'),
        'theme' => 'views_view_rss',
  		'uses row plugin' => TRUE,
        'uses options' => TRUE,
        'type' => 'feed',
        'help topic' => 'style-rss',
      ),
    ),
  );
  return $plugins;
}
// $Id$

/**
 * Required so Views will load the default views for this module.
 */
function oer_feed_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'oer_feed') .'/includes',
  );
}
