<?php
// $Id$

/**
 * Implementation of hook_form_FORM_ID_alter() for user_profile_form.
 */
function clear_password_field_form_user_profile_form_alter(&$form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'clear_password_field') . '/clear_password_field_edit.js');
}

/**
 * Implementation of hook_form_FORM_ID_alter() for user_register.
 */
function clear_password_field_form_user_register_alter(&$form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'clear_password_field') . '/clear_password_field_register.js');
}
